### ISSUE TITLE
Not showing any errors if vscode typescript validation is disabled and eslint enabled

### ISSUE THREAD

**Issue by jpsantos7** [yoavbls/pretty-ts-errors#67]
**Describe the bug**
If a setting as such is used:
```
{
  "typescript.validate.enable": false, // <- this is the setting
  "eslint.validate": [
    "javascript",
    "javascriptreact",
    "typescript",
    "typescriptreact"
  ]
}
```
no errors pretty-ts-errors are displayed. only the ESLint ones as shown in the following image:

<img width="960" alt="Screenshot 2023-06-21 at 23 12 52" src="https://github.com/yoavbls/pretty-ts-errors/assets/1482804/71d97a1f-9d47-47f2-aaeb-bca42ad65584">

If we change this to `true` we now get all **3 validations:** which is not desirable:

<img width="960" alt="Screenshot 2023-06-21 at 23 12 31" src="https://github.com/yoavbls/pretty-ts-errors/assets/1482804/16c611f1-0008-4f1f-bc83-c028c0da08ea">

**Expected behavior**
Being able to use the following setting and still be able to see the pretty errors and probably the eslint errors, but not the ts ones:
```
{
  "typescript.validate.enable": false
}
```

**Comment by kas1qqqq** [comment]
plx fix =)

**Comment by yoavbls** [comment]
Hey @jpsantos7,
The extension can't work when the TypeScript validation is disabled because it uses that errors to generate the formatted ones. Unfortunately, until something changes in VSCode we can't hide the original messages, even though we want. 
We're tacking it here: https://github.com/yoavbls/pretty-ts-errors/issues/3

And someone else asked about formatting eslint errors. I haven't seen a point in that since the errors are pretty simple and not containing complex types but I'm willing to consider it if I'll see a good example
